receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

processors:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - logging
