name: CI

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: swift:5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel
  compile-example:
    runs-on: ubuntu-latest
    container: swift:5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Open Example
        run: cd Example
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build
        run: swift build --enable-test-discovery
